- debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: MAGMA | join cluster nodes
  sudo: true
  shell: 'cd /usr/lib/erlang/lib/magma; {{item}}'
  with_items:
    - bin/magma-admin cluster join 'node1@192.168.33.10'
    - bin/magma-admin cluster plan
    - bin/magma-admin cluster commit
  #when: erld_downloaded.changed
