# file: tasks/magma_erld.yml

- name: ERLD | Download ERLD sources
  git: repo={{ erld_repo_url }} dest="/tmp/erld" accept_hostkey=yes
  sudo: true
  register: erld_downloaded

- name: ERLD | bootsrap | configure | install
  sudo: true
  shell: 'cd /tmp/erld; {{item}}'
  with_items:
    - ./bootstrap.sh
    - ./configure
    - make
    - make install
  # when: erld_downloaded.changed

- name: ERLD | make dir for magma daemon
  sudo: true
  file: path=/etc/magmad state=directory mode=0755
  # when: magma_downloaded.changed

- name: ERLD | make /var/log/magmad
  sudo: true
  file: path=/var/log/magmad state=directory mode=0755
  # when: magma_downloaded.changed

- name: ERLD | add cookie
  sudo: true
  action: template src=cookie-template.j2 dest=/etc/magmad/cookie mode=0400
  # when: magma_downloaded.changed

# - name: ERLD | add erld init.d
#   sudo: true
#   action: template src=magmad.init-template.j2 dest=/etc/init.d/magmad mode=0755
#   # when: magma_downloaded.changed

# - name: ERLD | Ensure the systemd directory exists
#   file:
#     name: "/etc/systemd/system/magmad.service.d"
#     state: directory
#     mode: 0755

- name: ERLD | Use the conf directory when starting magma
  sudo: true
  action: template src=magmad.serviced-template.j2 dest=/etc/systemd/system/magmad.service

- name: reload systemd
  command: systemctl daemon-reload

# - name: ERLD | add erld systemd script
#   sudo: true
#   action: template src=magmad.init-template.j2 dest=/etc/init.d/magmad mode=0755

- name: EPMD | Start epmd
  sudo: true
  service: name=epmd.socket state=started

- name: ERLD | Start erld
  sudo: true
  service: name=magmad state=restarted
  # when: magma_downloaded.changed
